version: "3"

services:

  embark_db:
    container_name: embark_db_dev
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - "3306"
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      embark_dev:
        ipv4_address: "172.21.0.5"

  redis:
    container_name: embark_redis_dev
    image: "redis:5"
    command: --port 7777
    expose:
      - "7777"
    ports:
      - "7777:7777"
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      embark_dev:
        ipv4_address: "172.21.0.8"
    logging:
      driver: "local"


networks:
  embark_dev:
    name: embark_dev
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: embark_dev
    ipam:
      config:
        - subnet: "172.21.0.0/16"

