version: "3"
services:
  auth-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"

  embark:
    image: embark:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
    volumes:
        - ${FIRMWARE}/:/firmware
        - ${LOG}/:/log
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/:/tmp/
        - ./embark/:/app/embark/
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
    env_file:
      - .env
    command: './entrypoint.sh'
    environment:
        - USER
    depends_on:
        - auth-db
        - redis

  redis:
    image: "redis:5"
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: "host"
