version: "3"
# still in work
services:

  embark_db:
    image: mysql
    container_name: embark_db
    restart: always
    expose:
      - "3306"
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      # - ./embark_db:/var/lib/mysql
    networks:
      - backend

  embark:
    image: embark:latest
    container_name: embark_server
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock # this is a BIG problem
        - ./embark/:/app/embark/
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
    networks:
      - embark_frontend
      - embark_backend
    env_file: 
      - .env
    command: './entrypoint.sh'
    depends_on:
        - embark_db
        - redis
        - emba

  emba:
    image: embeddedanalyzer/emba:latest
    build: ./emba
    privileged: true
    volumes:
      - ${FIRMWARE_EMBA}/:/firmware
      - ${LOG_EMBA}/:/log
      - ${EMBA}/:/emba:ro
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - embark_backend
    environment:
      - USER
    devices:
      - /dev/fuse:/dev/fuse:rwm
    cap_add:
      - SYS_ADMIN

  redis:
    image: "redis:5"
    container_name: embark_redis
    command: --port 7777
    expose:
      - "7777"
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - embark_backend

networks:
  embark_frontend:
    name: embark_frontend
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: embark_frontend

  embark_backend:
    name: embark_backend
    driver: ipvlan
    internal: true
    ipam:
      config:
        - subnet: "172.22.0.0/16"


