version: "3"

services:
  embark_db:
    image: mysql
    container_name: embark_db
    restart: always
    expose:
      - "3306"
    env_file:
      - .env
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - embark_backend

  embark:
    image: embark:latest
    container_name: embark_server
    build: .
    restart: always
    privileged: true
    env_file:
      - .env
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock 
        - ./emba/:/app/emba/
        - /etc/timezone:/etc/timezone:ro
        - /etc/localtime:/etc/localtime:ro
    ports:
      - "80:80"
      - "8001:8001"
      - "443:443"
    networks:
      - embark_backend
    environment:
      - TODO
    command: './entrypoint.sh'
    depends_on:
        - embark_db
        - redis

  redis:
    image: "redis:5"
    container_name: embark_redis
    command: --port 7777
    env_file:
      - .env
    expose:
      - "7777"
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      - embark_backend

networks:
  embark_backend:
    name: embark_backend_docker
    driver: bridge
    ipam:
      config:
        - subnet: "172.23.0.0/16"


