version: "3"
services:
  auth-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    network_mode: "host"
    ports:
      - '3306:3306'

  embark:
    image: embark:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    privileged: true
    volumes:
        - ${FIRMWARE}/:/firmware
        - ${LOG}/:/log
        - /var/run/docker.sock:/var/run/docker.sock
        - /tmp/:/tmp/
        - ./embark/:/app/embark/
    network_mode: "host"
    ports:
      - '80:80'
      - '8001:8001'
    env_file:
      - .env
    command: './entrypoint.sh'
    environment:
        - USER
    depends_on:
        - auth-db
        - redis

  redis:
    image: "redis:5"
    restart: always
    network_mode: "host"
    ports:
      - '6379:6379'
