version: "3"

services:
  auth-db:
    container_name: embark_db_dev
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - .env
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      embark_dev:
        aliases:
          - embark_db_dev

  redis:
    container_name: embark_redis_dev
    image: "redis:5"
    command: --port 7777
    restart: always
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    networks:
      embark_dev:
        aliases:
          - embark_redis_dev 


networks:
  embark_dev:
    name: embark_dev
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: embark_dev

