# This workflow will run build embark in dev-mode

name: Build-Embark-DEV 

on: [push]
  
jobs:
  Build-embark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v2 
    - name: Run build
      run: |
        sudo ./installer.sh -d
        ./embark/runserver.sh 
        
