# This workflow will run build embark in dev-mode

name: Build-Embark-DEV 

on: [push]
  
jobs:
  Build-embark:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v2 
    - name: Install Python, pipenv and Pipfile packages
      uses: palewire/install-python-pipenv-pipfile@v2
      with:
        python-version: 3.9
    - name: Install-deps
      run: |
        sudo apt install -y python3-django python3-dev  
        sudo apt install -y build-essential default-libmysqlclient-dev
    - name: Get externals
      run: |
          mkdir -p ./embark/static/external/{scripts,css}
          wget -O ./embark/static/external/scripts/jquery.js https://code.jquery.com/jquery-3.6.0.min.js
          wget -O ./embark/static/external/scripts/confirm.js https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js
          wget -O ./embark/static/external/scripts/bootstrap.js https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js
          wget -O ./embark/static/external/scripts/datatable.js https://cdn.datatables.net/v/bs5/dt-1.11.2/datatables.min.js
          wget -O ./embark/static/external/scripts/charts.js https://cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js
          wget -O ./embark/static/external/css/confirm.css https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css
          wget -O ./embark/static/external/css/bootstrap.css https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css
          wget -O ./embark/static/external/css/datatable.css https://cdn.datatables.net/v/bs5/dt-1.11.2/datatables.min.css
          find ./embark/static/external/ -type f -exec sed -i '/sourceMappingURL/d' {} \;
      shell: bash
    - name: Get Emba
      run: git clone https://github.com/e-m-b-a/emba.git
    - name: Start Debugg-server-conf
      run: bash ./dev-tools/debug-start-server.sh
      timeout-minutes: 5
