# This workflow will run build embark in dev-mode

name: Build-Embark-DEV 

on: [push]
  
jobs:
  Build-embark:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the Code
      uses: actions/checkout@v2
    - run: echo "checkt out ${{ github.repository }} - Now in $0 " 
    - name: Run build
      run: |
        cd embark
        sudo installer.sh -d
        ./embark/runserver.sh 
        
