# This workflow will run the Python testcases

name: Test [Python 3.7]

on: push

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]

    steps:
    - uses: actions/checkout@v2
    - name: Build using Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies [pip]
      run: |
        cd embark
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: run unit tests [pytest]
      run: cd embark && python manage.py test && cd ..
