# This workflow tests the project for proper linting

name: Lint with pycodestyle (former pep8) [ Python 3.7 ]

on: push

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]

    steps:
    - uses: actions/checkout@v2
    - name: Build using Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies [pip]
      run: |
        cd embark
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: run linter [pycodestyle (former PEP8)]
      run: pycodestyle .

