# This workflow tests the project for proper linting

name: Lint and check all

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies for linting
      run: |
        sudo apt-get install -y python3-dev npm pycodestyle pylint python3-pylint-django
        sudo npm install -g jshint
      shell: bash
    - name: Run checkproject
      run: sudo ./dev-tools/check_project.sh
      shell: bash

