# This workflow tests the project for proper linting

name: Lint and check all

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Branch
      uses: actions/checkout@v2
    - name: Install dependencies for linting
      run: |
        sudo apt-get install -y python3-dev npm pycodestyle pylint python3-pylint-django bandit
        sudo npm install -g jshint
    - name: Install Python, pipenv and Pipfile packages
      uses: palewire/install-python-pipenv-pipfile@v2
      with:
        python-version: 3.8
      shell: bash
    - name: Run checkproject
      run: |
        sudo pipenv run ./dev-tools/check_project.sh

